# Generated by Django 4.0.2 on 2022-04-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('purchasing_officer', models.CharField(max_length=200, null=True)),
                ('eic', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('project_name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('top', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
