# Generated by Django 4.0.2 on 2022-05-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JBW_File_Manage_System_APP', '0010_alter_quotation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codex', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
