# Generated by Django 4.0.2 on 2022-05-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JBW_File_Manage_System_APP', '0009_remove_quotation_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Done Service', 'Done Service'), ('On going', 'On going')], max_length=200, null=True),
        ),
    ]
